### PR TITLE
Rebuild the list, improvements in build.js

### PR DESCRIPTION
**Pull request by IonicaBizau**
I improved the build script to try to get the GitHub token from the `~/.github-config.json` file used by [`cli-github`](https://github.com/IonicaBizau/cli-github). So, passing a token as command line argument is not mandatory anymore (as long you use `cli-github`). 🚀 

@alysonla Currently we get here only the public members from the @GitHub organisation. I have an ~~evil~~ amazing plan to scrape the `/about/team` page (which contains **all** the members) and then use GitHub API to get the full names. I recently open-sourced [`scrape-it`](https://github.com/IonicaBizau/scrape-it) which would do a good job here. 😁

### CODE REVIEW

**Comment by IonicaBizau** [comment]
Welcome to the board, @djdefi, @donokuda, @jkrmr, @jleaver, @kavgan, @lee-dohm, @LizzHale, @mikrobi, @mistydemeo, @paladique, @pravipati, @simurai, @sridharavinash, @stoe, @tma, @WillAbides and last but not least, the amazing @zeke! 😁 🎉 ✨ 💫 

<sub>Honestly, I think few of you only publicised the membership in the organisation and became visible via the API. Hello anyways! 😄 </sub>

**Comment by alysonla** [comment]
Thanks @IonicaBizau ! Public GitHub org members are more than sufficient and for privacy reasons I wouldn't want to include anyone that isn't a public member anyway. 

I haven't had a chance to run this but it looks fine so happy to merge. 🚙 

Also, hi :octocat:s ! Hope you might find this game useful pre-summit! 😅 Despite being slow to respond, additional PRs welcome!

**Comment by zeke** [comment]
👋

**Comment by IonicaBizau** [comment]
@alysonla @zeke You're welcome! 🚀 In the past, `/humans.txt` was returning a geeky response with all the GitHub team (pretty much the text version of the `/about/team` page), but now it redirects to `/about`... 😁

**Pull request merged**
