### PR TITLE
New GitHubbers!

### PR DESCRIPTION
**Pull request by IonicaBizau**
Just ran the build script and it seems that quite few new nice people appeared. :rocket: 

Also it looks like some of the old users quit GitHub or concealed their membership to the organization.

Welcome @cheshire137, @davidcelis, @ethomson, @fernandez, @frconil, @gnawhleinad, @jessicard, @jwiebalk, @stevecat and @tarebyte! :tada: :grin:

### CODE REVIEW

**Comment by cheshire137** [comment]
+1 :)

**Comment by jessicard** [comment]
Woohoo! :smile_cat:

**Comment by gnawhleinad** [comment]
:wave:!

**Comment by jwiebalk** [comment]
:+1: :wave:

**Comment by davidcelis** [comment]
✌🏽

**Comment by guntrip** [comment]
:cat::wave:

**Comment by IonicaBizau** [comment]
Haha, I never received so many +1s from GitHubbers in one discussion, before. :joy:

**Comment by alysonla** [comment]
Yaay all the new :octocat: s! :wave: :tada: 

Thanks @IonicaBizau for the PR! (I need to apparently adjust my email notifications..)

**Comment by IonicaBizau** [comment]
@alysonla :blush:

**Pull request merged**
